### ISSUE TITLE
도로명으로 mark를 못하니 좌표로 해야함

### ISSUE THREAD

**Issue by tofulim** [vail131/foodmap#19]

**Comment by Golchic** [comment]
네이버 참고 주소 : https://api.ncloud-docs.com/docs/ai-naver-mapsgeocoding-geocode
위에 주소 cors localhost:3000 등록해야 지 가지고 x,y 좌표 가지고 올 수 있을꺼 같아요

**Comment by Golchic** [comment]
[tofulim](https://github.com/tofulim)

**Comment by tofulim** [comment]
front에서 cors에러로 좌표 api 못부르면 backend에서 db에 박아서 제공하는 것 고려

**Comment by tofulim** [comment]
- [ ] todo1

**Comment by Golchic** [comment]
<img width="791" alt="Screen Shot 2024-03-12 at 2 30 29 PM" src="https://github.com/tofulim/foodmap/assets/94821721/e951b437-b75b-4a1f-837f-d42738802a89">
아주 골치 아픈 에러가 있었네요 ㅋㅋㅋㅋ

**Comment by tofulim** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋ 저런 그렇다면 제가 박아두겠습니다

**Comment by Golchic** [comment]
![Screen Shot 2024-03-12 at 5 42 34 PM](https://github.com/tofulim/foodmap/assets/94821721/ca34b7d5-1eae-4eca-9fe1-9f91c933f2a2)
api 매번 호출보단 db 저장이 더 괜찮아 보여요

**Comment by tofulim** [comment]
좌표는 geo_location 이라는 key에 tuple로 [x, y] 이렇게 들어가 있습니다. @Johnny-tunib 

<img width="684" alt="image" src="https://github.com/tofulim/foodmap/assets/52443401/858c0b8f-c860-4af8-ba58-13f3bcb07a67">
